AllCops:
  RunRailsCops: true
  Exclude:
    - 'lib/tasks/cucumber.rake'
    - 'config/unicorn.rb'
    - 'db/**/*'
    - 'Guardfile'
    - 'vendor/bundle/**/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 45
# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 112

# We don't use this often but sometimes it improves readability
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: false
